# Generated by Django 4.1.4 on 2023-02-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='siteName',
            field=models.JSONField(),
        ),
    ]
