# Generated by Django 4.1.4 on 2023-02-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblock', '0002_alter_site_sitename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entertainment', models.TextField()),
                ('social', models.TextField()),
                ('news', models.TextField()),
                ('sports', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
