# Generated by Django 4.1.4 on 2023-02-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='work_time_hours',
            new_name='hrs',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='work_time_minutes',
            new_name='mins',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='todoTitle',
        ),
    ]
