# Generated by Django 4.1.4 on 2023-02-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_work_time_hours_todo_hrs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='break_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='work_cycle',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='work_time',
            field=models.IntegerField(null=True),
        ),
    ]
